# INNER JOIN SQL SCRIPT

#SYNTAX:
/*
SELECT COLUMNS FROM TABLE_1 INNER JOIN TABLE_2 
ON TABLE_1.COLUMN_NAME = TABLE_2.COLUMN_NAME;
				|					|
			FOREIGN KEY			PRIMARY KEY
*/
DROP DATABASE SIB16;
CREATE DATABASE SIB16;
USE SIB16;

#DROP TABLE CITY;
CREATE TABLE CITY(
	CID INT NOT NULL,
    CITY_NAME VARCHAR(30),
    PRIMARY KEY(CID)
    );
    
INSERT INTO CITY (CID,CITY_NAME)
VALUES
(1,'PUNE'),
(2,'MUMBAI'),
(3,'LATUR');


#DROP TABLE STUDENT;
CREATE TABLE STUDENT(
	ID INT NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    PHONE BIGINT NOT NULL,
    AGE INT NOT NULL CHECK(AGE>=18),
    CITY INT NOT NULL DEFAULT 1,
	FOREIGN KEY (CITY) REFERENCES CITY(CID)
    );
    
INSERT INTO STUDENT (ID,NAME,PHONE,AGE,CITY)
VALUES
(100,'AMAN',1231231231,20,1),
(101,'ADITYA',8976542341,21,2),
(102,'ASHFAQ',345543342,21,3),
(103,'SOHAM',7896543458,20,1),
(104,'AIRAF',8976785463,21,1),
(105,'ANIL',1234562345,20,2);

SELECT * FROM sib16.city;
SELECT * FROM sib16.student;

#APPLYING INNER JOIN
# SELECT * FROM STUDENT INNER JOIN CITY 
# ON STUDENT.CITY = CITY.CID;

SELECT S.ID,S.NAME,S.PHONE,S.AGE,C.CITY_NAME FROM STUDENT S INNER JOIN CITY C
ON S.CITY = C.CID
WHERE C.CITY_NAME = "PUNE"
ORDER BY S.NAME;

# S = ASLISE NAME FOR TABLE STUDENT
# C ALISE NAME FOR TABLE CITY

