DROP DATABASE STUDENT_MANAGEMENT;
CREATE DATABASE STUDENT_MANAGEMENT;
USE STUDENT_MANAGEMENT;

-- DROP TABLE STUDENT;
CREATE TABLE STUDENT(
    STUDENT_NO BIGINT NOT NULL,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    PRIMARY KEY (STUDENT_NO)
);

-- TRUNCATE TABLE STUDENT;
INSERT INTO STUDENT (STUDENT_NO,FIRST_NAME, LAST_NAME) 
VALUES 
(1,'RAKESH', 'VARMA'),
(2,'KRISHNA','BHANDALKAR'),
(3,'OM','LALWANE'),
(4,'OMKAR','KOKNE');

SELECT * FROM STUDENT;

CREATE TABLE COURSE(
	COURSE_ID BIGINT NOT NULL,
    COURSE_NAME VARCHAR(30),
    PRIMARY KEY(COURSE_ID)
);

INSERT INTO COURSE(COURSE_ID,COURSE_NAME)
VALUES
(100,'C++'),
(101,'JAVA'),
(102,'PYTHON'),
(103,'MYSQL'),
(104,'HTML');

SELECT * FROM COURSE;

CREATE TABLE ENROLL(
	STUDENT_NO BIGINT NOT NULL,
    COURSE_ID BIGINT NOT NULL,
    PRIMARY KEY(STUDENT_NO,COURSE_ID),
    FOREIGN KEY ENROLL(STUDENT_NO) REFERENCES STUDENT(STUDENT_NO) ON DELETE CASCADE,
	FOREIGN KEY ENROLL(COURSE_ID) REFERENCES COURSE(COURSE_ID) ON DELETE CASCADE
);

INSERT INTO ENROLL(STUDENT_NO,COURSE_ID)
VALUES
(1,101),
(2,101),
(2,102),
(3,100);

SELECT * FROM ENROLL
ORDER BY(STUDENT_NO);

DELETE FROM STUDENT
WHERE STUDENT_NO = 1;

