DROP DATABASE EMPLOYEE;
CREATE DATABASE EMPLOYEE; 
USE EMPLOYEE;

CREATE TABLE MANAGER (
    MANAGER_ID VARCHAR(10),
    MANAGER_NAME VARCHAR(50),
    MANAGER_EMAIL VARCHAR(50),
    MANAGER_PHONE VARCHAR(50),
    PRIMARY KEY(MANAGER_ID,MANAGER_EMAIL)
);
DESC MANAGER;

INSERT INTO MANAGER(MANAGER_ID,MANAGER_NAME,MANAGER_EMAIL,MANAGER_PHONE)
VALUES
('M-12','JHON WICK','jhon@email.com',1112221234),
('M-10','MOHAN LAL','mohan@email.com',4445556661);


CREATE TABLE DEPARTMENT (
	
    DEPARTMENT_ID BIGINT NOT NULL,
    DEPARTMENT_NAME VARCHAR(30) NOT NULL,
    PRIMARY KEY(DEPARTMENT_ID)
    
);

DESC DEPARTMENT;

INSERT INTO DEPARTMENT (DEPARTMENT_ID,DEPARTMENT_NAME)
VALUES
(1,'DEVELOPER'),
(2,'DATA MANAGEMENT'),
(3,'DATA ANALYTICS');


CREATE TABLE EMPLOYEE_INFO (
	
    EMPLOYEE_ID INT NOT NULL,
    EMPLOYEE_NAME VARCHAR(30) NOT NULL,
    EMPLOYEE_PHONE BIGINT NOT NULL,
    EMPLOYEE_CITY VARCHAR(30) NOT NULL,
    EMPLOYEE_DEPARTMENT BIGINT NOT NULL,
    MANAGER_ID VARCHAR(10),
	PRIMARY KEY(EMPLOYEE_ID,EMPLOYEE_PHONE),
    FOREIGN KEY(EMPLOYEE_DEPARTMENT) REFERENCES DEPARTMENT(DEPARTMENT_ID),
    FOREIGN KEY(MANAGER_ID) REFERENCES MANAGER(MANAGER_ID)
);

DESC EMPLOYEE_INFO;

INSERT INTO EMPLOYEE_INFO (EMPLOYEE_ID,EMPLOYEE_NAME,EMPLOYEE_PHONE,EMPLOYEE_CITY,EMPLOYEE_DEPARTMENT,MANAGER_ID) 
VALUES
(100,'JHON WICK',1009123452,'PUNE',1,'M-12'),
(100,'JHON WICK',1231234321,'PUNE',3,'M-12'),
(101,'SALMAN KHAN',1786549873,'MUMBAI',2,NULL),
(101,'SALMAN KHAN',1236541246,'MUMBAI',1,NULL),
(102,'MOHAN LAL',1236548761,'DELHI',3,'M-10'),
(103,'SUMAN VARMA',176456432,'DELHI',2,NULL);

SELECT * FROM EMPLOYEE.DEPARTMENT;
SELECT * FROM EMPLOYEE.MANAGER;
SELECT * FROM EMPLOYEE.EMPLOYEE_INFO;

SELECT * FROM EMPLOYEE.EMPLOYEE_INFO
WHERE EMPLOYEE_ID = 100;

SELECT * FROM EMPLOYEE.EMPLOYEE_INFO
WHERE EMPLOYEE_ID = 101;

SELECT * FROM EMPLOYEE.EMPLOYEE_INFO
WHERE EMPLOYEE_ID = 102;

SELECT * FROM EMPLOYEE.EMPLOYEE_INFO
WHERE EMPLOYEE_ID = 103;