/*
	DELIMITER $$
	CREATE PROCEDURE Procedure_Name()
		BEGIN
			SELECT * FROM table_name; -- example
		END $$
	DELIMITER ;

*/
DROP DATABASE PL_SQL;
CREATE DATABASE PL_SQL;
USE PL_SQL;

CREATE TABLE STUDENT(
	STUDENT_ID INT NOT NULL,
    STUDENT_NAME VARCHAR(100) NOT NULL,
    STUDENT_AGE INT DEFAULT 28,
    PRIMARY KEY (STUDENT_ID)
);

INSERT INTO STUDENT (STUDENT_ID,STUDENT_NAME,STUDENT_AGE)
VALUES
(101,'MANOJ KEDAR',20),
(102,'VIRAT KOHLI',20),
(103,'RAM SHUKLA',21),
(104,'RAJU RASTOGI',19),
(105,'JAMES HOLAND',20);

DELIMITER $$
CREATE PROCEDURE get_student()
	BEGIN
		SELECT * FROM STUDENT;
	END $$
DELIMITER ;

CALL GET_STUDENT();

ALTER TABLE STUDENT
ADD COLUMN PERSENTAGE DECIMAL(10,2);

UPDATE STUDENT
SET PERSENTAGE = 60
WHERE STUDENT_ID = 101;

UPDATE STUDENT
SET PERSENTAGE = 70
WHERE STUDENT_ID = 102;

UPDATE STUDENT
SET PERSENTAGE = 50
WHERE STUDENT_ID = 103;

UPDATE STUDENT
SET PERSENTAGE = 65
WHERE STUDENT_ID = 104;

UPDATE STUDENT
SET PERSENTAGE = 60
WHERE STUDENT_ID = 105;

/*
-- 1 MAX(COLUMN_NAME)
SELECT MAX(PERSENTAGE) AS PERSENTAGE FROM STUDENT;

-- 2 MIN(COLUMN_NAME)
SELECT MIN(PERSENTAGE) AS PERSENTAGE FROM STUDENT;

-- 3 AVG(COLUMN_NAME)
SELECT AVG(PERSENTAGE) AS PERSENTAGE FROM STUDENT;

*/
-- ==============================================================================================================
DELIMITER $$
CREATE PROCEDURE GET_MAX_PERSENT()
	BEGIN
		SELECT MAX(PERSENTAGE) AS PERSENTAGE FROM STUDENT;
    END $$
DELIMITER ;

CALL GET_MAX_PERSENT();

-- =============================================================================================================== 

DELIMITER $$
CREATE PROCEDURE GET_MIN_PERSENT()
	BEGIN
		SELECT MIN(PERSENTAGE) AS PERSENTAGE FROM STUDENT;
    END $$
DELIMITER ;

CALL GET_MIN_PERSENT();

-- ==============================================================================================================

DELIMITER //
CREATE PROCEDURE GET_AVERAGE_PERSENT()
	BEGIN
		SELECT AVG(PERSENTAGE) AS PERSENTAGE FROM STUDENT;
    END //
DELIMITER ;

CALL GET_AVERAGE_PERSENT();

-- ==============================================================================================================

DELIMITER &&
CREATE PROCEDURE FIND_STUDENT(IN ID INT)
	BEGIN
		SELECT * FROM STUDENT
        WHERE STUDENT_ID = ID;
    END &&
DELIMITER ;

CALL FIND_STUDENT(101);

-- ==============================================================================================================

DELIMITER &&
CREATE PROCEDURE DELETE_STUDENT(IN ID INT)
	BEGIN
		DELETE FROM STUDENT 
        WHERE STUDENT_ID = ID;
    END &&
DELIMITER ;

CALL DELETE_STUDENT(101);
CALL GET_STUDENT();
-- ==============================================================================================================
DESC STUDENT;

DELIMITER &&
CREATE PROCEDURE INSERT_STUDENT(IN ID INT,NAME VARCHAR(80),AGE INT,PERSENTAGE DECIMAL(10,2))
	BEGIN
		INSERT INTO student(STUDENT_ID,STUDENT_NAME,STUDENT_AGE,PERSENTAGE)
        VALUES(ID,NAME,AGE,PERSENTAGE);
    END &&
DELIMITER ;

CALL INSERT_STUDENT(101,'AMAN MUJAWAR',20,80.6);
CALL GET_STUDENT();

CALL INSERT_STUDENT(106,'SALMAN JAMADAR',19,89);
CALL INSERT_STUDENT(107,'SUSHANT SUTAR',20,90);
CALL INSERT_STUDENT(108,'TANVEER BHALDAR',20,80);

CALL GET_STUDENT();

CALL FIND_STUDENT(108);